"profiles":
  get:
    summary: プロフィール取得
    description: ログインアカウントに紐づくプロフィール情報を取得する。
    tags:
      - プロフィール
    security:
      - bearerAuth: []
    responses:
      "200":
        description: 正常終了
        content:
          "application/json":
            schema:
              $ref: "../components/schemas/profiles.yml#/profile"
      "401":
        description: API認証エラー (※ [API Gatewayから返却される](https://aws.amazon.com/jp/premiumsupport/knowledge-center/api-gateway-cognito-401-unauthorized/)）
        content:
          "application/json":
            schema:
              $ref: "../components/schemas/errors.yml#/error"
      "403":
        description: 実行権限エラー （※ [Amazon S3](https://aws.amazon.com/jp/premiumsupport/knowledge-center/s3-troubleshoot-403/)や[AWS WAF](https://dev.classmethod.jp/articles/aws-waf-custom-errorpage/)、[API Gateway](https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/api-gateway-gatewayResponse-definition.html)から403エラー返却される場合がある）
        content:
          "application/json":
            schema:
              $ref: "../components/schemas/errors.yml#/error"
      "404":
        description: 指定された情報が見つからない
        content:
          "application/json":
            schema:
              $ref: "../components/schemas/errors.yml#/error"
      "500":
        description: サーバーエラー
        content:
          "application/json":
            schema:
              $ref: "../components/schemas/errors.yml#/error"
